### ISSUE TITLE
Add support to filter/show recently used messages types

### ISSUE THREAD

**Issue by jramoyo** [jramoyo/quickfix-messenger#3]
[Migrated from Google Code](https://code.google.com/p/quickfix-messenger/issues/detail?id=54)

Update the messages list to support showing the recently used messages

**Comment by DerekYangYC** [comment]
The enhancement has been committed to derek-dev branch.

Please help to review and merge to master

**Comment by jramoyo** [comment]
Looks good! Merged to master branch...
